[language-server.rust-analyzer.config]
checkOnSave = { overrideCommand = ["cargo", "lint"] }
files = { excludeDirs = [".flatpak-builder"] }

[language-server.texlab.config.texlab.build]
executable = "tectonic"
args = ["-X", "compile", "%f"]
onSave = true
